// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 04/01/2026, 16:11:34
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/local-git/073145.github.io/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/local-git/073145.github.io/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/local-git/073145.github.io/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/local-git/073145.github.io/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/local-git/073145.github.io/src/plugins/**/*.{js,ts,mjs}","D:/local-git/073145.github.io/src/composables/**/*.{js,ts,mjs}","D:/local-git/073145.github.io/src/utils/**/*.{js,ts,mjs}","D:/local-git/073145.github.io/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/local-git/073145.github.io/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/local-git/073145.github.io/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;